---
title: "Data integrity checks"
author: "Yota"
date: "28 3 2022"
output: workflowr::wflow_html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/shared/datalake/mapme.protectedareas")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results="hide"}
# clean workspace, set options
rm(list=ls())


# get packages
lop <- c("tidyverse","sf", "leaflet", "leaflet.extras", "leaflet.extras2", "ggsci", "scales", "htmltools", "RColorBrewer", "stargazer")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)
```



```{r NA analysis in matching frames, echo=FALSE, warning=FALSE, message=FALSE}
#------- Load matching frames --------

# Years with matching frames:
T_year <- c(2003:2020)
# T_year <- c(2006)

# Create table rows
count_na_row <- c()
count_na_treat_row <- c() 
count_na_control_row <- c()

complete_table <- rep(NA,14)
treat_na_pct_table <- rep(NA,14)
control_na_pct_table <- rep(NA,14)

for (i in T_year) {
  file <- paste0("matching_frame_",i)
  df <- 
    read_csv(paste("./output/matching/matching_frames/matching_frame_",i,".csv", sep = "")) %>% 
    select(id, poly_id, treatment, everything())
  assign(file, df)
  
  # Check for NA values
  obs_count <- sapply(get(file), function(y) length(y))
  na_count <-sapply(get(file), function(y) sum(length(which(is.na(y)))))
  obs_count_treat <-sapply(subset(get(file), get(file)$treatment==1), function(y) length(y))
  na_count_treat <-sapply(subset(get(file), get(file)$treatment==1), function(y) sum(length(which(is.na(y)))))
  na_pct_treat <-  sapply(subset(get(file), get(file)$treatment==1), function(y) sum(length(which(is.na(y))))/length(y))
  obs_count_control <-sapply(subset(get(file), get(file)$treatment==0), function(y) length(y))
  na_count_control <-sapply(subset(get(file), get(file)$treatment==0), function(y) sum(length(which(is.na(y)))))
  na_pct_control <-  sapply(subset(get(file), get(file)$treatment==0), function(y) sum(length(which(is.na(y))))/length(y))
  na_count_table <- cbind(obs_count, na_count, 
                          obs_count_treat, na_count_treat, na_pct_treat, 
                          obs_count_control, na_count_control, na_pct_control)
  
  file2 <- paste0("table_countNA_",i)
  assign(file2, na_count_table)
  
  # stargazer(na_count_table,
  #           summary=FALSE,
  #           type="text",
  #           title = paste0("Number of missing values in treatment and control cells for ", i),
  #           out = paste0("./output/matching/output_tables/count_missing/table_countNA_",i,".html"))
  
  # create table with all years
  complete_table <- cbind(complete_table, obs_count,na_count,
                          obs_count_treat, na_count_treat, na_pct_treat,
                          obs_count_control, na_count_control)
  
  treat_na_pct_table <- cbind(treat_na_pct_table, na_pct_treat)
  control_na_pct_table <- cbind(control_na_pct_table, na_pct_control)
  
  
}

complete_table <- complete_table[,-1]

# Table with pct of NAs in treatment group
treat_na_pct_table <- treat_na_pct_table[,-1]
treat_na_pct_table <- as.data.frame(treat_na_pct_table)
colnames(treat_na_pct_table) <- c(T_year)

names <- rownames(treat_na_pct_table)
rownames(treat_na_pct_table) <- NULL
treat_na_pct_table <- cbind(names,treat_na_pct_table)

# Table with pct of NAs in control group
control_na_pct_table <- control_na_pct_table[,-1]
control_na_pct_table <- as.data.frame(control_na_pct_table)
colnames(control_na_pct_table) <- c(T_year)

names <- rownames(control_na_pct_table)
rownames(control_na_pct_table) <- NULL
control_na_pct_table <- cbind(names,control_na_pct_table)
```

### Plot NA percentages (treatment group)

```{r NA in treated, echo=FALSE, warning=FALSE, message=FALSE}
treat_na_pct_table %>% 
  filter(names != c("id","poly_id","treatment")) %>% 
  pivot_longer(!names,
               names_to="year",
               values_to="na_pct_treat") %>% 
  ggplot() +
  geom_line(aes(x=year, y=(na_pct_treat*100), group=names, col=names),
            lwd=2, alpha=0.7) +
  labs(y = "Percentage of NA values per variable [%]",
       color = "Variable") +
  theme(legend.position="bottom")
```


### Plot NA percentages (control group)

```{r NA in control, echo=FALSE, warning=FALSE, message=FALSE}
control_na_pct_table %>% 
  filter(names != c("id","poly_id","treatment")) %>% 
  pivot_longer(!names,
               names_to="year",
               values_to="na_pct_control") %>% 
  ggplot() +
  geom_line(aes(x=year, y=(na_pct_control*100), group=names, col=names),
            lwd=2, alpha=0.7) +
  labs(y = "Percentage of NA values per variable [%]",
       color = "Variable") +
  theme(legend.position="bottom")
```


### Map with treated polygons in 2006

Check if there are wrongly assigned treatment cells in the matching frames. 

```{r map mf 2006, echo=FALSE, warning=FALSE, message=FALSE}
##  Protected areas
wdpa_kfw<-
  read_sf("~/shared/datalake/mapme.protectedareas/input/wdpa_kfw/wdpa_kfw_spatial_latinamerica_2021-02-01_supportedPAs_unique.gpkg")

# Load KfW finance data 
kfw_finance <- 
  read_csv("~/shared/datalake/mapme.protectedareas/input/kfw_finance/mapme.protectedareas_kfw-finance-2021-03-17.csv") %>% 
  filter(! is.na(bmz_nummer))

#Load wdpa bmz keys
keys_wdpaid_bmz <- read_csv("~/shared/datalake/mapme.protectedareas/output/matching/model_frames/keys_wdpaid_bmz.csv") %>% 
  rename("bmz_nummer" = "value")

# merge wdpa_kfw with keys
wdpa_kfw <- left_join(wdpa_kfw, keys_wdpaid_bmz,
                      by=c("WDPAID"))

#add kfw_finance data to wdpa_kfw
wdpa_kfw <- left_join(wdpa_kfw, kfw_finance, 
                      by=c("bmz_nummer"))

## fishnet
fishnet <-
  read_sf(
    "../../datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_all_update_Dec-07.gpkg")

# fishnet for merge
mf_fishnet <- fishnet

# Years with matched panels:
# T_year <- c(2004, 2006:2013, 2015, 2016, 2019)
T_year <- c(2006)

#data before matching
for (i in T_year) {
  #data after matching
  df <- 
    read_csv(paste("./output/matching/matching_frames/matching_frame_",i,".csv", sep = ""),
             col_types = cols(wdpa_id = col_character(),
                              bmz_nummer = col_character())) #%>% 
    #filter(treatment == 1)
  # assign(file2, df2)
  
  mf_fishnet <- inner_join(mf_fishnet, df, by=c("poly_id"))
  
  wdpa_kfw <- wdpa_kfw %>% 
    filter(first_year == i)
}

mf_fishnet <- st_transform(mf_fishnet,crs = st_crs(wdpa_kfw))

# Look at treated polygons only
mf_fishnet <- mf_fishnet %>% 
  filter(treatment.x == 1)

#------- Color palettes --------

# create colorramp2
pal_match <- colorFactor(
  palette = c("darkblue","green"),
  domain = mf_fishnet$treatment.x
)

#------- Map --------

## Create map
# wdpa_kfw_treatment_centroid<-st_transform(st_centroid(wdpa_kfw_treatment_centroid),crs = 4326)
my_map_matching <-
  leaflet() %>%
  # add external map providers
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles(providers$CartoDB.Positron, group="CartoDB") %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$Esri.WorldShadedRelief, group="Topography") %>%
  addProviderTiles(providers$NASAGIBS.ViirsEarthAtNight2012, group="Nightlights") %>%
  # add own data
  addPolygons(data = wdpa_kfw,opacity = 0.9,color = "orange", group = "PA Boundaries (all years)",label = ~htmlEscape(NAME),weight = 1)%>%
  addPolygons(data = mf_fishnet, opacity = 0.9, color = ~pal_match(treatment.x), 
              group = "Treated polygons",label = ~htmlEscape(poly_id),weight = 1) %>%
  addFullscreenControl() %>%
addLegend("bottomright",
          data = mf_fishnet,
          pal = pal_match,
          values = ~treatment.x,
          # labels = c("not matched", "matched"),
          title = "Treated polygons",
          opacity = 1,
          group = "Treated polygons") %>%
# add layers control to define which data is shown or ommited in default view
addLayersControl(
  baseGroups = c("CartoDB","OpenStreetMap","Satellite","Topography","Nightlights"), #"Toner",,"Regional Primary Forests (2001)"
  overlayGroups = c("PA Boundaries (all years)", "Treated polygons"),
  options = layersControlOptions(collapsed = FALSE)) %>%
  # ommit certain layers
  hideGroup(group = c("Country","PA Area Size","Cells (Treamtent & Control) in 2015","Forest Cover Loss (2001-2020)"))

my_map_matching

```

