---
title: "Regression analysis with stacked panel"
author: "Melvin H. L. Wong"
date: "1 9 2022"
output: workflowr::wflow_html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/shared/datalake/mapme.protectedareas")
```

```{r include=FALSE}
# clean workspace, set options
rm(list=ls())
options(scipen=999)
options(width = 200)

# get packages
lop <- c("dplyr", "plm", "stargazer", "tidyverse", "cem", "multiwayvcov", "modelsummary", "fixest", "kableExtra")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)

```

```{r}
panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn1.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_1.df <- panel.df

panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn2.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_2.df <- panel.df

# panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn3.rds")
# panel.df$stack <- substring(panel.df$stack_id,1,4)
# panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
# panel_3.df <- panel.df

panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn4.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_4.df <- panel.df


panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn5.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_5.df <- panel.df

panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn6.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_6.df <- panel.df

panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_iucn7.rds")
panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
panel_7.df <- panel.df

m1 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_1.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

m2 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_2.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

#m3 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_3.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)
# note: This regression does not work, because of perfect collinearity with FE. Too few data variation

m4 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_4.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

m5 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_5.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

m6 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_6.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

m7 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_7.df, weights = ~weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)

m_list1 <- list(m1, m2, m4, m5, m6, m7)
names(m_list1) <- c("(1) Protection", " (2) Management", "(4) Education", "(5) Law/Policy", "(6) Livelihood", "(7) Capacity")

modelsummary(m_list1,
             output = "/datadrive/datalake/mapme.protectedareas/output/tabular/regression_output/tn_projects/table_tn_iucn.tex",
             coef_rename = c("fc_area" = "Forest cover area", 
                             "treatment_disbTRUE" = "KfW support"),
             stars = TRUE,
             gof_map = c("nobs", "adj.r.squared", "FE: stack_id", "FE: year"),
             title = paste0("Dependent variable: Forest cover area"),
             notes = list('Standard errors clustered by zones of forest protected areas (WDPA).')
)


modelsummary(m_list1,
             output = "/datadrive/datalake/mapme.protectedareas/output/tabular/regression_output/tn_projects/table_tn_iucn.html",
             coef_rename = c("fc_area" = "Forest cover area", 
                             "treatment_disbTRUE" = "KfW support"),
             stars = TRUE,
             gof_map = c("nobs", "adj.r.squared", "FE: stack_id", "FE: year"),
             title = paste0("Dependent variable: Forest cover area"),
             notes = list('Standard errors clustered by zones of forest protected areas (WDPA).')
)

modelsummary(m_list1,
             coef_rename = c("fc_area" = "Forest cover area", 
                             "treatment_disbTRUE" = "KfW support"),
             stars = TRUE,
             gof_map = c("nobs", "adj.r.squared", "FE: stack_id", "FE: year"),
             title = paste0("Dependent variable: Forest cover area"),
             notes = list('Standard errors clustered by zones of forest protected areas (WDPA).')
)



```

```{r}
panel.df <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_all.rds")


panel.df$stack <- substring(panel.df$stack_id,1,4)
panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 

fpf <- c(199867003, 199867219, 200065086, 200165472, 200266908, 200466094, 200466458, 200865444, 200866285, 200866657, 201065143, 201166156, 201167063, 201265685, 201367127,201567957, 201768464, 209810094, 209810854, 209810961)
panel_fpf.df <- filter(panel.df, bmz_nummer %in% fpf) 
  
m1 <-   feols(fc_loss ~ treatment_disb | stack_id + year, data = panel_fpf.df, weights = panel_fpf.df$weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)
m2 <-   feols(fc_area ~ treatment_disb | stack_id + year, data = panel_fpf.df, weights = panel_fpf.df$weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)
m3 <-   feols(emissions_tha ~ treatment_disb | stack_id + year, data = panel_fpf.df, weights = panel_fpf.df$weights_cem, panel.id = ~stack_id+year, cluster = ~WDPAID_cluster_stack)




m_list1 <- list(m1, m2, m3)
names(m_list1) <- c("Loss", "Area", "Emissions")
modelsummary(m_list1,
             coef_rename = c("fc_loss" = "Forest cover loss", 
                             "treatment_disbTRUE" = "KfW support"),
             stars = TRUE,
             gof_map = c("nobs", "adj.r.squared", "FE: stack_id", "FE: year"),
             title = paste0("Dependent variable: Forest cover loss"),
             notes = list('Standard errors clustered by zones of forest protected areas (WDPA).')
)
```

