---
title: "Create stacked panel"
author: "Melvin H. L. Wong"
date: "1 9 2022"
output: workflowr::wflow_html
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "/datadrive/datalake/mapme.protectedareas")
```


```{r workspace and packages}
# clean workspace, set options
rm(list=ls())
options(scipen=999)

# get packages
lop <- c("tidyverse", "sf", "units", "dplyr")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)

```


```{r stack Panel datasets}
# list of panel datasets
all_years <- list.files("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects") %>% 
  grep("cem_tn_matched_panel_*", ., value = TRUE)
bmz_list <- all_years %>% 
    gsub("cem_tn_matched_panel_", "", .) %>% 
    gsub(".csv", "", .)

bmz_list <- bmz_list[-which(bmz_list=="199566829"| bmz_list=="199966649")] # skip entries that cause issues because of perfect collinearity of treatment variable
bmz_list <- bmz_list[-which(bmz_list=="201066661")] #skip because of coastal and marine protection without any forest cover
# load each list entry and create unique panel id across all matching frames


#### first half
bmz_list1 <- bmz_list[1:round(length(bmz_list)/2, 0)] # select only first half of all matching frames

big.list.of.data.frames <- lapply(bmz_list1, function(x){
  file <- list(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", x, ".csv"))
  read_csv(file) %>% 
  mutate(stack_id=paste0(x, .assetid)) %>% 
    select(stack_id, .assetid, WDPAID, treatment, weights, fc_loss, fc_area, emissions, year, NAME_0, year_standard, bmz_nummer, class1, class2, class3, class4, class5, class6, class7)
})
# rbind all dataframes together
big.data.frame <- do.call(rbind,big.list.of.data.frames)


 panel.df <- big.data.frame %>% 
    mutate(treatment_disb = (treatment==1 & year_standard>=0),
           emissions_tha = emissions/500,
           NAME_0_num = as.numeric(as.factor(NAME_0))) %>% 
    rename(., weights_cem=weights) # rename weights
  # create WDPA cluster that are country specific (important for control group, as all controll cells belong to ID 9999999999 regardless of the country. Now the control cells are clustered for each country.)
  panel.df$WDPAID_cluster <- as.numeric(paste0(panel.df$NAME_0_num, panel.df$WDPAID)) 
  panel.df$stack <- substring(panel.df$stack_id,1,4)
  panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
  
  
  panel.df <- as.data.frame(panel.df)
  
  # save big file
  saveRDS(panel.df, file="/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_01n.rds")
  
  # clean up RAM
  rm(big.list.of.data.frames)
  rm(big.data.frame)
  rm(panel.df)  
  
  
######## part 2
bmz_list2 <- bmz_list[-which(bmz_list==bmz_list1)] # select only second half of all matching frames
bmz_list_loop <- bmz_list2[1:3]  # select only second half of all matching frames


big.list.of.data.frames <- lapply(bmz_list_loop, function(x){
  file <- list(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", x, ".csv"))
  read_csv(file) %>% 
  mutate(stack_id=paste0(x, .assetid)) %>% 
    select(stack_id, .assetid, WDPAID, treatment, weights, fc_loss, fc_area, emissions, year, NAME_0, year_standard, bmz_nummer, class1, class2, class3, class4, class5, class6, class7)
})
# rbind all dataframes together
big.data.frame <- do.call(rbind,big.list.of.data.frames)


 panel.df <- big.data.frame %>% 
    mutate(treatment_disb = (treatment==1 & year_standard>=0),
           emissions_tha = emissions/500,
           NAME_0_num = as.numeric(as.factor(NAME_0))) %>% 
    rename(., weights_cem=weights) # rename weights
  # create WDPA cluster that are country specific (important for control group, as all controll cells belong to ID 9999999999 regardless of the country. Now the control cells are clustered for each country.)
  panel.df$WDPAID_cluster <- as.numeric(paste0(panel.df$NAME_0_num, panel.df$WDPAID)) 
  panel.df$stack <- substring(panel.df$stack_id,1,4)
  panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
  
  panel.df <- as.data.frame(panel.df)  
  
  # save big file
  saveRDS(panel.df, file="/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_02n.rds")
  
  
  
######## part 3
bmz_list_loop <- bmz_list2[4:7]  # select only second half of all matching frames


big.list.of.data.frames <- lapply(bmz_list_loop, function(x){
  file <- list(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", x, ".csv"))
  read_csv(file) %>% 
  mutate(stack_id=paste0(x, .assetid)) %>% 
    select(stack_id, .assetid, WDPAID, treatment, weights, fc_loss, fc_area, emissions, year, NAME_0, year_standard, bmz_nummer, class1, class2, class3, class4, class5, class6, class7)
})
# rbind all dataframes together
big.data.frame <- do.call(rbind,big.list.of.data.frames)


 panel.df <- big.data.frame %>% 
    mutate(treatment_disb = (treatment==1 & year_standard>=0),
           emissions_tha = emissions/500,
           NAME_0_num = as.numeric(as.factor(NAME_0))) %>% 
    rename(., weights_cem=weights) # rename weights
  # create WDPA cluster that are country specific (important for control group, as all controll cells belong to ID 9999999999 regardless of the country. Now the control cells are clustered for each country.)
  panel.df$WDPAID_cluster <- as.numeric(paste0(panel.df$NAME_0_num, panel.df$WDPAID)) 
  panel.df$stack <- substring(panel.df$stack_id,1,4)
  panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
  
  panel.df <- as.data.frame(panel.df)  
  
  # save big file
  saveRDS(panel.df, file="/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_03n.rds")
  
  
  
  
######## part 4
bmz_list_loop <- bmz_list2[8:16]  # select only second half of all matching frames


big.list.of.data.frames <- lapply(bmz_list_loop, function(x){
  file <- list(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", x, ".csv"))
  read_csv(file) %>% 
  mutate(stack_id=paste0(x, .assetid)) %>% 
    select(stack_id, .assetid, WDPAID, treatment, weights, fc_loss, fc_area, emissions, year, NAME_0, year_standard, bmz_nummer, class1, class2, class3, class4, class5, class6, class7)
})
# rbind all dataframes together
big.data.frame <- do.call(rbind,big.list.of.data.frames)


 panel.df <- big.data.frame %>% 
    mutate(treatment_disb = (treatment==1 & year_standard>=0),
           emissions_tha = emissions/500,
           NAME_0_num = as.numeric(as.factor(NAME_0))) %>% 
    rename(., weights_cem=weights) # rename weights
  # create WDPA cluster that are country specific (important for control group, as all controll cells belong to ID 9999999999 regardless of the country. Now the control cells are clustered for each country.)
  panel.df$WDPAID_cluster <- as.numeric(paste0(panel.df$NAME_0_num, panel.df$WDPAID)) 
  panel.df$stack <- substring(panel.df$stack_id,1,4)
  panel.df$WDPAID_cluster_stack <- as.numeric(paste0(panel.df$stack, panel.df$NAME_0_num, panel.df$WDPAID)) 
  
  
  panel.df <- as.data.frame(panel.df)  
  # save big file
  saveRDS(panel.df, file="/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_04n.rds")

```
```{r}
stack01 <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_01n.rds")
stack01 <- as.data.frame(stack01)
stack02 <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_02n.rds")
stack02 <- as.data.frame(stack02)
stack03 <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_03n.rds")
stack03 <- as.data.frame(stack03)
stack04 <- read_rds("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_04n.rds")
stack04 <- as.data.frame(stack04)


all.df <- rbind(stack01, stack02, stack03, stack04)
all.df <- as.data.frame(all.df)
  saveRDS(all.df, file="/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/cem_matched_data_stacked_projects_all.rds")
```

