---
title: "Testing parallel trends - Project level data"
author: "Melvin HL Wong"
date: "24 10 2022"
output: workflowr::wflow_html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "~/shared/datalake/mapme.protectedareas")
```

```{r options and workspace}
# clean workspace, set options
rm(list=ls())
options(scipen=999)

# get packages
lop <- c("dplyr", "plm", "stargazer", "tidyverse", "MatchIt", "optmatch", "cobalt", "gridExtra", "grid", "gtable", "dplyr")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)

# # set working directory
# setwd("~/shared/datalake/mapme.protectedareas")
```

## Absolute forest cover 

Note: Values correspond to weighted averages of absolute forest cover in treatment and control cells, respectively. 

```{r create plots in pdf, include=TRUE}
all_years <- list.files("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects") %>% 
  grep("cem_tn_matched_panel_*", ., value = TRUE)

bmz_list <- all_years %>% 
    gsub("cem_tn_matched_panel_", "", .) %>% 
    gsub(".csv", "", .)

bmz_list <- bmz_list[-which(bmz_list=="199566829"| bmz_list=="199966649")] # skip entries that cause issues because of perfect collinearity of treatment variable


# create PDF with plots
# pdfpath <- "/datadrive/datalake/mapme.protectedareas/output/plots/parallel_trends_tn/cem_fc.pdf"
# pdf(file=pdfpath)

for (bmz in bmz_list) {
  
  
    # Load matching frame 
  
  mf <- read_rds(paste0("/datadrive/datalake/mapme.protectedareas/output/matching/matching_frames/projects/matching_frame_", bmz, ".rds")) %>% 
    select(.assetid, treatment, starts_with("treecover")) %>% 
    pivot_longer(cols = c(starts_with("treecover")),
                 names_to = c(".value", "year"),
                 names_sep = "_") %>% 
    rename("fc_area" = "treecover") %>% 
    mutate(year = as.numeric(year))
    
  mf_summarized <- 
    mf %>% 
    group_by(year, treatment) %>% 
    summarise(mean_fca = mean(fc_area, na.rm = TRUE))
  
  mf_min <- min(mf_summarized$mean_fca, na.rm = TRUE)
  mf_max <- max(mf_summarized$mean_fca, na.rm = TRUE)
  

  
  # Load CEM panel
  
  mp_cem <- 
    read_csv(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", bmz, ".csv")) %>% 
    mutate(fc_area_weighted = fc_area * weights)
  
  t_year <- unique(mp_cem$first_year)
  t_year <- t_year[!is.na(t_year)]
  
  mp_summarized_cem <- 
    mp_cem %>% 
    group_by(year, treatment) %>% 
    summarise(mean_fca = mean(fc_area_weighted))
  
  cem_min <- min(mp_summarized_cem$mean_fca, na.rm = TRUE)
  cem_max <- max(mp_summarized_cem$mean_fca, na.rm = TRUE)
  
  
label_yearfirst <- unique(mp_cem$first_year_bmz)
  # Load PSM panel 
  
  # mp_psm <- 
  #   read_csv(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/PSM/tn_projects/psm_tn_matched_panel_", bmz, ".csv")) %>% 
  #   mutate(fc_area_weighted = fc_area * weights)
  # 
  # 
  # mp_summarized_psm <- 
  #   mp_psm %>% 
  #   group_by(year, treatment) %>% 
  #     summarise(mean_fca = mean(fc_area_weighted))
  # 
  # psm_min <- min(mp_summarized_psm$mean_fca, na.rm = TRUE)
  # psm_max <- max(mp_summarized_psm$mean_fca, na.rm = TRUE)
  
  
  
  # Create plots
  
  # ymin <- min(cem_min, psm_min)
  # ymax <- max(cem_max, psm_max)  
  
  ymin <- min(cem_min, mf_min)
  ymax <- max(cem_max, mf_max)
  
  
    avg_plot_mf <- 
    mf_summarized %>% 
    ggplot() +
    geom_line(aes(x = year, 
                  y = mean_fca,
                  col = as.factor(treatment),
                  group = treatment)) + 
    geom_vline(xintercept = label_yearfirst, col = "red", linetype = "dashed") +
    coord_cartesian(ylim = c(ymin, ymax)) +
    labs(title=paste0("Before matching"),
         x ="Year", y = "Absolute forest cover (ha)") +
    theme(legend.position = "bottom") +
    scale_colour_discrete(name= "", breaks=c("0", "1"),
                          labels=c("Control", "Treated")) + 
    scale_x_continuous(breaks = seq(2000, 2020, by = 4))
    
    
  avg_plot_cem <- 
    mp_summarized_cem %>% 
    ggplot() +
    geom_line(aes(x = year, 
                  y = mean_fca,
                  col = as.factor(treatment),
                  group = treatment)) + 
    geom_vline(xintercept =  label_yearfirst, col = "red", linetype = "dashed") +
    coord_cartesian(ylim = c(ymin, ymax)) +
    labs(title=paste0("CEM"),
         x ="Year", y = "") +
    theme(legend.position = "bottom") +
    scale_colour_discrete(name= "", breaks=c("0", "1"),
                          labels=c("Control", "Treated")) + 
    scale_x_continuous(breaks = seq(2000, 2020, by = 4))
  
  avg_plot_cem_zoom <- 
    mp_summarized_cem %>% 
    ggplot() +
    geom_line(aes(x = year, 
                  y = mean_fca,
                  col = as.factor(treatment),
                  group = treatment)) + 
    geom_vline(xintercept =  label_yearfirst, col = "red", linetype = "dashed") +
    coord_cartesian(ylim = c(cem_min, cem_max)) +
    labs(title=paste0("CEM - Detail"),
         x ="Year", y = "") +
    theme(legend.position = "bottom") +
    scale_colour_discrete(name= "", breaks=c("0", "1"),
                          labels=c("Control", "Treated")) + 
    scale_x_continuous(breaks = seq(2000, 2020, by = 4))
  
  # avg_plot_psm <- 
  #   mp_summarized_psm %>% 
  #   ggplot() +
  #   geom_line(aes(x = year, 
  #                 y = mean_fca,
  #                 col = as.factor(treatment),
  #                 group = treatment)) + 
  #   geom_vline(xintercept =  as.integer(t), col = "red", linetype = "dashed") +
  #   coord_cartesian(ylim = c(ymin, ymax)) +
  #   labs(title=paste0("PSM (BMZ: ",  bmz, ")"),
  #        x ="Year", y = "") +
  #   theme(legend.position = "bottom") +
  #   scale_colour_discrete(name= "", breaks=c("0", "1"),
  #                         labels=c("Control", "Treated")) + 
  #   scale_x_continuous(breaks = seq(2000, 2020, by = 4))
  # 
  # grid.arrange(avg_plot_cem, avg_plot_psm, 
  #              ncol = 2)
  print(bmz)
  




  grid.arrange(avg_plot_mf, avg_plot_cem, avg_plot_cem_zoom, ncol = 3, heights=c(6,1,1), top =bmz)

  

  
  grid.arrange(avg_plot_mf, avg_plot_cem_zoom, ncol = 2)
  grid.arrange(avg_plot_cem_zoom, ncol = 1)
  

}

#dev.off()

```

