---
title: "Balance Descriptives"
author: "Yota"
date: "28 3 2022"
output: workflowr::wflow_html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "/datadrive/datalake/mapme.protectedareas")
```

```{r include=FALSE}
# clean workspace, set options
rm(list=ls())
options(scipen=999)
options(width = 200)

# get packages
lop <- c("dplyr", "plm", "stargazer", "tidyverse", "MatchIt", "optmatch", "cobalt", "gridExtra", "sf")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)

```

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r summary stats for projects }
# Timer
start_time <- Sys.time()

all_years <- list.files("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects") %>% 
  grep("cem_tn_matched_panel_*", ., value = TRUE)
bmz_list <- all_years %>% 
    gsub("cem_tn_matched_panel_", "", .) %>% 
    gsub(".csv", "", .)

bmz_list <- bmz_list[-which(bmz_list=="199566829"| bmz_list=="199966649")] # skip entries that cause issues because of perfect collinearity of treatment variable
bmz_list <- bmz_list[-which(bmz_list=="201066661")] #skip because of coastal and marine protection without any forest cover

# Prepare observations table
obs_table <- matrix(NA, nrow = length(bmz_list), ncol = 7)
colnames(obs_table) <- c("Country", "PA in ha.", "No. PA", "Project years", "Disbursement (mil. EUR)", "Share strict IUCN", "IUCN category" )
rownames(obs_table) <- c(bmz_list)





# Load link between assetid and WDPA ID
keys_assetid_wdpa <- 
  read_sf("~/shared/datalake/mapme.protectedareas/processing/fishnet/honeycomb_5_sqkm_kfw.gpkg") %>% 
  select(poly_id, WDPAID) %>% 
  rename(".assetid" = "poly_id") %>% 
  st_drop_geometry()



for (bmz in bmz_list) {

      print(bmz)
         panel.df <- read.csv(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", bmz, ".csv"), sep = ",", stringsAsFactors = F)
        
    
      
       # Country
      iso <- unique(panel.df$NAME_0) %>% 
        na.omit(.) %>% 
        paste(., collapse = " ")
      obs_table[paste0(bmz), 1] <- iso
       iso <- NA #delete vector to avoid writing wrong information into table
      
   
      # PA in ha
      pre.df <- read_rds(paste0("/datadrive/datalake/mapme.protectedareas/output/matching/matching_frames/projects/matching_frame_", bmz, ".rds"))%>% merge(., keys_assetid_wdpa, by=".assetid", all.x=T) %>% select(WDPAID, treatment)
      # calculate area within PA (number of unique cells time 500 ha per cell)
      treat_ha <- length(which(pre.df$treatment==1))*500 
      treat_ha <- format(round(as.numeric(treat_ha), 0), nsmall=0, big.mark=",")  #format decimal points
      obs_table[paste0(bmz), 2] <- treat_ha
      treat_ha <- NA #delete vector to avoid writing wrong information into table
      

     
      # No. PA
      no_pa <- unique(panel.df$WDPAID) 
      no_pa[which(no_pa==9999999999)] <- NA
      
      no_pa <- no_pa %>% 
        na.omit(.) %>% 
        as.numeric() %>% 
        length()
      obs_table[paste0(bmz), 3] <- no_pa
       no_pa <- NA #delete vector to avoid writing wrong information into table
  
     # years
     start_y <- unique(panel.df$first_year_bmz)
     end_y <- unique(panel.df$last_year_bmz)
     table_years <- paste(start_y, end_y, collapse = " ")
     obs_table[paste0(bmz), 4] <- table_years
     table_years  <- NA
   
     # Disbursement (EUR)
    bmz_disb <- unique(panel.df$total_disbursed) %>% 
    na.omit(.) %>% 
      as.data.frame() %>% 
      mutate(.=round(./1000000,1))
    bmz_disb <- paste(bmz_disb, collapse = " ")
    obs_table[paste0(bmz), 5] <- bmz_disb
    bmz_disb <- NA #delete vector to avoid writing wrong information into table
  
  
  
     # Share strict IUCN
 
      ##calculate share of IUCN strict categories
      strict_share_list <- panel.df %>%
        select(WDPA_strict) %>% 
        na.omit(.) %>% 
        group_by(WDPA_strict) %>%
        summarise(cnt = n()) %>%
        mutate(freq = round(cnt / sum(cnt), 3)) %>% 
        arrange(desc(freq)) %>% 
        select(-cnt) %>% 
        as.data.frame()
      
      ## get info which element is strict WDPA
      iucn_strict <- strict_share_list[which(strict_share_list$WDPA_strict==1),2]
      
      if(length(iucn_strict)==0){
        obs_table[paste0(bmz), 6] <- 0
        } else{
          obs_table[paste0(bmz), 6] <- iucn_strict
        }
     iucn_strict <- NA #delete vector to avoid writing wrong information into table
    
    # IUCN category
    iucn_share_list <- panel.df %>%
      select(IUCN_CAT) %>% 
      na.omit(.) %>% 
      mutate(IUCN_CAT = replace(IUCN_CAT, IUCN_CAT == "Not Reported", "n/a"),
             IUCN_CAT = replace(IUCN_CAT, IUCN_CAT == "Not Applicable", "n/a"),
             IUCN_CAT = replace(IUCN_CAT, IUCN_CAT == "Not Assigned", "n/a")) %>%
      group_by(IUCN_CAT) %>%
      summarise(cnt = n()) %>%
      mutate(freq = round(cnt / sum(cnt), 2)) %>% 
      arrange(desc(freq)) %>% 
      select(-cnt)
  
    iucn_cat <- paste(iucn_share_list$IUCN_CAT, iucn_share_list$freq, collapse = " ")
  
  
    obs_table[paste0(bmz), 7] <- iucn_cat
    iucn_cat <- NA #delete vector to avoid writing wrong information into table
    
 
}



stargazer(obs_table, out = "/datadrive/datalake/mapme.protectedareas/output/tabular/descriptive/desc_proj.tex", notes = " ")



```
```{r balancing tables}

all_years <- list.files("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects") %>% 
  grep("cem_tn_matched_panel_*", ., value = TRUE)
bmz_list <- all_years %>% 
    gsub("cem_tn_matched_panel_", "", .) %>% 
    gsub(".csv", "", .)

bmz_list <- bmz_list[-which(bmz_list=="199566829"| bmz_list=="199966649")] # skip entries that cause issues because of perfect collinearity of treatment variable
bmz_list <- bmz_list[-which(bmz_list=="201066661")] #skip because of coastal and marine protection without any forest cover
#bmz_list <- bmz_list[1:3]
# bmz <- bmz_list[6]



# Prepare observations table
obs_table <- matrix(1, nrow = length(bmz_list), ncol = 12)
colnames(obs_table) <- c("C", "T", "C", "T", "C", "T", "C", "T", "C", "T", "C", "T")
rownames(obs_table) <- c(bmz_list)




for (bmz in bmz_list) {

      print(bmz)
         panel.df <- read.csv(paste0("/datadrive/datalake/mapme.protectedareas/output/tabular/regression_input/CEM/tn_projects/cem_tn_matched_panel_", bmz, ".csv"), sep = ",", stringsAsFactors = F) %>% 
           filter(first_year_bmz==year) %>% # get cross sectional data of time invariant matching variables
           select(traveltime_5k_110mio,
                  m_treecover,
                  m_loss_tn,
                  soil_5_15cm_clay,
                  terrain_ruggedness_index_mean,
                  elevation_mean,
                  treatment,
                  weights) 
         
         stats <- panel.df %>% 
           group_by(treatment) %>%
           summarise(traveltime_5k_110mio = weighted.mean(traveltime_5k_110mio, weights),
                      m_treecover  = weighted.mean(m_treecover, weights),
                      m_loss_tn  = weighted.mean(m_loss_tn, weights),
                      soil_5_15cm_clay  = weighted.mean(soil_5_15cm_clay, weights),
                     terrain_ruggedness_index_mean= weighted.mean(terrain_ruggedness_index_mean, weights),
                      elevation_mean = weighted.mean(elevation_mean, weights),
                     ) 
        
        # "Forest cover"
        obs_table[paste0(bmz), 1] <- as.character(round(stats$m_treecover[which(stats$treatment==0)], 1)) # control
        obs_table[paste0(bmz), 2] <- as.character(round(stats$m_treecover[which(stats$treatment==1)], 1)) # treatment
        
        # "Forest cover loss" 
        obs_table[paste0(bmz), 3] <- as.character(round(stats$m_loss_tn[which(stats$treatment==0)], 2)) # control
        obs_table[paste0(bmz), 4] <- as.character(round(stats$m_loss_tn[which(stats$treatment==1)], 2)) # treatment        
        
        
        # "Accessibility" 
        obs_table[paste0(bmz), 5] <- as.character(round(stats$traveltime_5k_110mio[which(stats$treatment==0)], 0)) # control
        obs_table[paste0(bmz), 6] <- as.character(round(stats$traveltime_5k_110mio[which(stats$treatment==1)], 0)) # treatment        
        

        
        # "Clay content" 
        obs_table[paste0(bmz), 7] <- as.character(round(stats$soil_5_15cm_clay[which(stats$treatment==0)], 0)) # control
        obs_table[paste0(bmz), 8] <- as.character(round(stats$soil_5_15cm_clay[which(stats$treatment==1)], 0)) # treatment       
        
        
        # "Terrain ruggedness" 
        obs_table[paste0(bmz), 9] <- as.character(round(stats$terrain_ruggedness_index_mean[which(stats$treatment==0)], 2)) # control
        obs_table[paste0(bmz), 10] <- as.character(round(stats$terrain_ruggedness_index_mean[which(stats$treatment==1)], 2)) # treatment        
        
        
        # "Elevation"
        obs_table[paste0(bmz), 11] <- as.character(round(stats$elevation_mean[which(stats$treatment==0)], 0)) # control
        obs_table[paste0(bmz), 12] <- as.character(round(stats$elevation_mean[which(stats$treatment==1)], 0)) # treatment
         
         
         
         
         
         
}



stargazer(obs_table, type = "latex", out = "/datadrive/datalake/mapme.protectedareas/output/tabular/descriptive/desc_balance_mean.tex")

c("Forest cover", "Forest cover loss", "Accessibility", "Clay content", "Terrain ruggedness", "Elevation")
```

