---
title: "The mapme.biodiversity package in R"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
workflowr:
  suppress_report: TRUE
---

In order to analyze your projects you will need geodata that represents your project area of interest (AOI). We matched our whole portfolio to the [World Database on Protected Areas (WDPA)](https://www.iucn.org/theme/protected-areas/our-work/quality-and-effectiveness/world-database-protected-areas-wdpa) from IUCN. You can use this database if you are working with protected areas and if you are aware of their name and location. There is also a R package called [wdpar](https://cran.r-project.org/web/packages/wdpar/index.html) that helps you to download the data in R and preprocess it to make it analysis ready. 

The WDPA already contains lots of meta-information about the protected areas which you can consult in the [WDPA manual](https://www.ibat-alliance.org/pdf/wdpa_manual.pdf).  
If you are working purely with protected areas from the WDPA you might also want to use data from the [Digital Observatory of Protected Areas (DOPA)](https://dopa.jrc.ec.europa.eu/dopa/) from the Joint Research Center of the European Union. We have create routines to download data which you can find in the other chapter (->Querying data from DOPA Rest API). 

We created an own R package to preprocess several variables relevant to biodiversity and conservation, the [mapme.biodiversity package](https://cran.r-project.org/web/packages/mapme.biodiversity/index.html). It contains different data-sets that are automatically downloaded for an area of interest and allows you to calculate summary statistics for your AOI (independently if your data comes from the WDPA or not). Currently our packages covers variables such as `tree cover ` and `tree cover loss` from the [Global Forest Watch](https://www.globalforestwatch.org/), `accessibility`, `elevation`, `climatic variables`, `land-cover` and others. Furthermore, we are also continously trying to add new variables. You can see planned improvements and suggest additional variables at our [github repository](https://github.com/mapme-initiative/mapme.biodiversity) in the "Issues" section. Using our package to create your own database is easy if you follow our [online-tutorials](https://mapme-initiative.github.io/mapme.biodiversity/index.html). 

A unique feature of our package is that it allows you to analyse very large portfolios using cloud-tecnologies and parallel processing approaches. It is furthermore convient to use, since it downloads data automatically for your AOI only which saves you manual downloading time and a lot of preprocessing routines such as stitching the data together and bringing them to a structured output format. 



